--create database Sito_Ecommerce

CREATE TABLE CLIENTE(
	ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE),
	NOME VARCHAR(50) NOT NULL,
	COGNOME VARCHAR(50) NOT NULL,
	DATA_DI_NASCITA DATETIME NOT NULL
);

CREATE TABLE PRODOTTO(
	ID_PRODOTTO INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT PK_PRODOTTO PRIMARY KEY(ID_PRODOTTO),
	CODICE_PRODOTTO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DESCRIZIONE VARCHAR(100) NOT NULL,
	PREZZO DECIMAL,
	QUANTITA_DISPONIBILE INT
);

CREATE TABLE CARTA(
	CODICE_CARTA CHAR(16) NOT NULL,
	CONSTRAINT PK_CARTA PRIMARY KEY(CODICE_CARTA),
	TIPO VARCHAR(30) NOT NULL,
	CONSTRAINT CHK_TIPO CHECK(TIPO = 'DEBITO' OR TIPO= 'CREDITO'),
	SCADENZA DATETIME NOT NULL,
	SALDO DECIMAL NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE INDIRIZZO(
	ID_INDIRIZZO INT IDENTITY (1,1) NOT NULL,
	CONSTRAINT PK_INDIRIZZO PRIMARY KEY(ID_INDIRIZZO),
	TIPO VARCHAR(30) NOT NULL,
	CONSTRAINT CHK_TIPO_INDIRIZZO CHECK (TIPO='RESIDENZA' OR TIPO ='DOMICILIO'),
	CITTA VARCHAR(50) NOT NULL,
	VIA VARCHAR(50)NOT NULL,
	CAP VARCHAR(10) NOT NULL,
	NUMERO_CIVICO VARCHAR(5) NOT NULL,
	PROVINCIA VARCHAR(50) NOT NULL,
	NAZIONE VARCHAR(50) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT FK_CLIENTE_DI_INDIRIZZO FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ORDINE (
	ID_ORDINE INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT PK_ORDINE PRIMARY KEY(ID_ORDINE),
	STATO VARCHAR(20) NOT NULL,
	DATA_ORDINE DATETIME NOT NULL,
	TOTALE DECIMAL NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_INDIRIZZO INT NOT NULL,
	CODICE_CARTA CHAR(16) NOT NULL,
	CONSTRAINT FK_CLIENTE_DI_ORDINE FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_INDIRIZZO FOREIGN KEY(ID_INDIRIZZO)
	REFERENCES INDIRIZZO(ID_INDIRIZZO),
	CONSTRAINT FK_CODICE_CARTA FOREIGN KEY(CODICE_CARTA)
	REFERENCES CARTA(CODICE_CARTA),
);

CREATE TABLE ORDINE_PRODOTTO (
	ID_ORDINE INT NOT NULL,
	ID_PRODOTTO INT NOT NULL,
	CONSTRAINT FK_ORDINE FOREIGN KEY(ID_ORDINE)
	REFERENCES ORDINE(ID_ORDINE),
	CONSTRAINT FK_PRODOTTO FOREIGN KEY(ID_PRODOTTO)
	REFERENCES PRODOTTO(ID_PRODOTTO),
	QUANTITA INT NOT NULL,
	SUBTOTALE DECIMAL NOT NULL
);


--STORE PROCEDURES --------------------------------------
--INSERT----------
--INSERT CLIENTE ,FARE TRANSAZIONE CON 3 INSERT(CARTA,INDIRIZZO ,CLIENTE)SE VA A BUON FINE SI IREGISTRA

CREATE PROCEDURE INSERT_CLIENTE
@NOME VARCHAR(50),
@COGNOME VARCHAR(50),
@DATA_NASCITA DATETIME,
@CODICECARTA CHAR(16),
@TIPO VARCHAR(30),
@SCADENZA DATETIME,
@SALDO DECIMAL,
@ID_CLIENTE INT,
@TIPO_IND VARCHAR(30),
@CITTA VARCHAR(50),
@VIA VARCHAR(50),
@CAP VARCHAR(10),
@NUMERO_CIVICO VARCHAR(5),
@PROVINCIA VARCHAR(50),
@NAZIONE VARCHAR(50),
@ID_CLIENTE_IND INT
AS
BEGIN TRY
BEGIN TRAN
	IF @SCADENZA <= CONVERT(DATE,GETDATE())
	SET @SCADENZA = NULL
	INSERT INTO CARTA VALUES(@CODICECARTA,@TIPO,@SCADENZA,@SALDO,@ID_CLIENTE);
	INSERT INTO INDIRIZZO VALUES (@TIPO_IND,@CITTA,@VIA,@CAP,@NUMERO_CIVICO,@PROVINCIA,@NAZIONE,@ID_CLIENTE_IND);
	INSERT INTO CLIENTE VALUES(@NOME,@COGNOME,@DATA_NASCITA);
COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
END CATCH
GO

SELECT * FROM CLIENTE

CREATE PROCEDURE INSERT_PRODOTTO
@CODICE_PRODOTTO INT,
@NOME VARCHAR(50),
@DESCRIZIONE VARCHAR(50),
@PREZZO DECIMAL,
@QUANTITA_DISP INT
AS
INSERT INTO PRODOTTO VALUES(@CODICE_PRODOTTO,@NOME,@DESCRIZIONE,@PREZZO,@QUANTITA_DISP);
GO

EXECUTE INSERT_PRODOTTO 00231,'JEANS','DENIM STRADIVARIUS',25.95,12
SELECT * FROM PRODOTTO

CREATE PROCEDURE INSERT_CARTA 
@CODICECARTA CHAR(16),
@TIPO VARCHAR(30),
@SCADENZA DATETIME,
@SALDO DECIMAL,
@ID_CLIENTE INT
AS
IF @SCADENZA <= CONVERT(DATE,GETDATE())
SET @SCADENZA = NULL
INSERT INTO CARTA VALUES(@CODICECARTA,@TIPO,@SCADENZA,@SALDO,@ID_CLIENTE)
GO

EXECUTE INSERT_CARTA 6002581200369851,'CREDITO','2020-01-28',80.00,1
SELECT * FROM CARTA

CREATE PROCEDURE INSERT_INDIRIZZO
@TIPO VARCHAR(30),
@CITTA VARCHAR(50),
@VIA VARCHAR(50),
@CAP VARCHAR(10),
@NUMERO_CIVICO VARCHAR(5),
@PROVINCIA VARCHAR(50),
@NAZIONE VARCHAR(50),
@ID_CLIENTE INT
AS
INSERT INTO INDIRIZZO VALUES (@TIPO,@CITTA,@VIA,@CAP,@NUMERO_CIVICO,@PROVINCIA,@NAZIONE,@ID_CLIENTE);
GO

EXECUTE INSERT_INDIRIZZO 'RESIDENZA','MILANO','VIA MONTENAPOLEONE',20145,59,'MILANO','ITALIA',1
SELECT * FROM INDIRIZZO

CREATE PROCEDURE INSERT_ORDINE --DA CREARE
@STATO VARCHAR(20),
@DATA_ORDINE DATETIME,
@TOTALE DECIMAL,
@FK_CLIENTE INT,
@FK_INDIRIZZO INT,
@FK_CODICECARTA CHAR(16)
AS 
INSERT INTO ORDINE VALUES(@STATO,@DATA_ORDINE,@TOTALE ,@FK_CLIENTE ,@FK_INDIRIZZO ,@FK_CODICECARTA)
GO

CREATE PROCEDURE INSERT_ORDINE_PRODOTTO --DA CREARE
@FK_ORDINE INT,
@FK_PRODOTTO INT,
@QUANTITA INT,
@SUBTOTALE DECIMAL
AS
INSERT INTO ORDINE_PRODOTTO VALUES(@FK_ORDINE,@FK_PRODOTTO,@QUANTITA,@SUBTOTALE);
GO